import type { Metadata } from 'next';
import './globals.css';
import Provider from '../components/Provider';
import TopNav from '@/components/navbar/TopNav';

export const metadata: Metadata = {
  title: 'Next Match App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Provider>
          <TopNav />
          <main className='container mx-auto'>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
